# Create a BOW table for the Brandon Sanderson Dataset

## Get Data to build `BOW` table

In [4]:
import pandas as pd
import numpy as np

directory_path  = 'C:/Users/mason/Box/Text As Data Final/Output'

In [6]:
CORPUS = pd.read_csv(directory_path + "/BrandonSanderson_CORPUS.csv", index_col=0)
CORPUS.head()

,title,chapter_id,paragraph_id,sent_id,token_id,token_str,term_str,pos,pos_group
0,A Memory of Light,0,0,0,0,The,the,DT,DT
1,A Memory of Light,0,0,0,1,Wheel,wheel,NNP,NN
2,A Memory of Light,0,0,0,2,of,of,IN,IN
3,A Memory of Light,0,0,0,3,Time,time,NNP,NN
4,A Memory of Light,0,0,0,4,turns,turns,NNS,NN

## Set the OHCO

In [8]:
OHCO = ['title', 'chapter_id', 'paragraph_id', 'sent_id', 'token_id']
bags = dict(
    SENTS = OHCO[:4],
    PARAS = OHCO[:3],
    CHAPS = OHCO[:2],
    BOOKS = OHCO[:1]
)
bag = 'CHAPS'

## Create the TOKEN table from CORPUS and save the OHCO

In [9]:
TOKEN = CORPUS.set_index(OHCO).dropna()
bags[bag]+['term_str']

['title', 'chapter_id', 'term_str']

In [10]:
BOW = TOKEN.groupby(bags[bag]+['term_str']).term_str.count().to_frame('n')
BOW.head()

                                          n
title             chapter_id term_str
A Memory of Light 0          a          141
                             abandoned    1
                             abilities    1
                             ability      1
                             able         4