# Create the `TFIDF` table for the Brandon Sanderson Dataset

## Get Data

In [1]:
import pandas as pd
import numpy as np

directory_path  = 'C:/Users/mason/Box/Text As Data Final/Output'

In [2]:
DTCM = pd.read_csv(directory_path + "/BrandonSanderson_DTCM.csv", index_col=['title', 'chapter_id'])
DTCM.head()

                              0  04  05  1  10  10010  10584  109thand  11  \
title             chapter_id
A Memory of Light 0           0   0   0  0   0      0      0         0   0
                  1           0   0   0  0   0      0      0         0   0
                  2           0   0   0  0   0      0      0         0   0
                  3           0   0   0  0   0      0      0         0   0
                  4           0   0   0  0   0      0      0         0   0

                              1167  ...  ﬂowers  ﬂuidity  ﬂush  ﬂushed  \
title             chapter_id        ...
A Memory of Light 0              0  ...       0        0     0       0
                  1              0  ...       0        0     0       0
                  2              0  ...       0        0     0       0
                  3              0  ...       0        0     0       0
                  4              0  ...       0        0     0       0

                              ﬂushedi  ﬂushing  ﬂushingi  ﬂushingit  \
title             chapter_id
A Memory of Light 0                 0        0         0          0
                  1                 0        0         0          0
                  2                 0        0         0          0
                  3                 0        0         0          0
                  4                 0        0         0          0

                              ﬂuttering  ﬂying
title             chapter_id
A Memory of Light 0                   0      0
                  1                   0      0
                  2                   0      0
                  3                   0      0
                  4                   0      0

[5 rows x 58423 columns]

## Define the `TFIDF` function

In [3]:
tf_method = 'sum'
tf_norm_k = .5
idf_method = 'standard'
gradient_cmap = 'YlGnBu'

In [4]:
print('TF method:', tf_method)

if tf_method == 'sum':
    TF = DTCM.T / DTCM.T.sum()

elif tf_method == 'smooth':
    TF = (DTCM.T / DTCM.T.sum()) + 1

elif tf_method == 'max':
    TF = DTCM.T / DTCM.T.max()
    
elif tf_method == 'log':
    TF = np.log2(1 + DTCM.T)
    
elif tf_method == 'raw':
    TF = DTCM.T
    
elif tf_method == 'double_norm':
    TF = ((DTCM.T + .5) / (DTCM.T.max() + .5)) + .5
    
elif tf_method == 'binary':
    TF = DTCM.T.astype('bool').astype('int')
    
TF = TF.T

TF method: sum

In [5]:
DF = DTCM.astype('bool').sum() 
DF

0            1
04           1
05           1
1            1
10           2
            ..
ﬂushing      3
ﬂushingi     1
ﬂushingit    1
ﬂuttering    1
ﬂying        1
Length: 58423, dtype: int64

In [6]:
N = DTCM.shape[0]

In [7]:
print('IDF method:', idf_method)

if idf_method == 'standard':
    IDF = np.log2(N / DF)

elif idf_method == 'max':
    IDF = np.log2(DF.max() / DF) 

elif idf_method == 'plus':
    IDF = np.log2(N / DF) + 1

# This is what SciKit Learn uses
elif idf_method == 'smooth':
    IDF = np.log2((1 + N) / (1 + DF)) + 1

IDF method: standard

In [8]:
TFIDF = TF * IDF
TFIDF.head()

                                0   04   05    1   10  10010  10584  109thand  \
title             chapter_id
A Memory of Light 0           0.0  0.0  0.0  0.0  0.0    0.0    0.0       0.0
                  1           0.0  0.0  0.0  0.0  0.0    0.0    0.0       0.0
                  2           0.0  0.0  0.0  0.0  0.0    0.0    0.0       0.0
                  3           0.0  0.0  0.0  0.0  0.0    0.0    0.0       0.0
                  4           0.0  0.0  0.0  0.0  0.0    0.0    0.0       0.0

                               11  1167  ...  ﬂowers  ﬂuidity  ﬂush  ﬂushed  \
title             chapter_id             ...
A Memory of Light 0           0.0   0.0  ...     0.0      0.0   0.0     0.0
                  1           0.0   0.0  ...     0.0      0.0   0.0     0.0
                  2           0.0   0.0  ...     0.0      0.0   0.0     0.0
                  3           0.0   0.0  ...     0.0      0.0   0.0     0.0
                  4           0.0   0.0  ...     0.0      0.0   0.0     0.0

                              ﬂushedi  ﬂushing  ﬂushingi  ﬂushingit  \
title             chapter_id
A Memory of Light 0               0.0      0.0       0.0        0.0
                  1               0.0      0.0       0.0        0.0
                  2               0.0      0.0       0.0        0.0
                  3               0.0      0.0       0.0        0.0
                  4               0.0      0.0       0.0        0.0

                              ﬂuttering  ﬂying
title             chapter_id
A Memory of Light 0                 0.0    0.0
                  1                 0.0    0.0
                  2                 0.0    0.0
                  3                 0.0    0.0
                  4                 0.0    0.0

[5 rows x 58423 columns]

## Save output as `TFIDF`

In [9]:
TFIDF.to_csv(directory_path + "/BrandonSanderson_TFIDF.csv")